### ISSUE TITLE
Slices and nested structs

### ISSUE THREAD

**Issue by wavded** [jszwec/csvutil#11]
Any thoughts on adding custom slice or map support? It would be nice to be able to have the option to custom encode those values rather than fail.

**Comment by jszwec** [comment]
Hello wavded,

I was considering it, but I didn't have a specific use case that it would solve. Could you share yours?

**Comment by wavded** [comment]
Sure, here is one example, just encoding a `[]string` value. In my case, clients would like it as such:

```
string,string_arr
value,"value_a,value_b"
```

But this could go for a slice of anything.

For maps, one example could be:

```
string,my_map
value, "key_a: val_a, key_v: val_b"
```

Essentially having some way to customize the output of those rather than fail would be helpful.

That make sense?

**Comment by jszwec** [comment]
Thank you for the example

I feel like it is impossible to determine what the *correct* default behavior for slices and maps is. There is no CSV spec for such values. Because of that everybody will expect it to do something different.

The most standard/default thing I can think of is to use `fmt.Print` on these values.

My personal opinion is that I would rather have no support for something than have a functionality that may satisfy a very small part of the community.

Unlike with other types, you don't have to cast slice aliases, so it is painless to use your own type
```go
package main

type Strings []string

func (s Strings) MarshalCSV() ([]byte, error) { return nil, nil }

type Foo struct {
	Strs Strings
}

func main() {
	strs := []string{"a", "b"}
	f := Foo{Strs: strs}
        ...
}
```

**Comment by wavded** [comment]
Yeah, I'd prefer not to wrap every slice struct and/or map with a custom type. I was more thinking along the lines of giving the user a function/config to handle the reflection themselves. But maybe my best route is to just write the CSV out by hand using `encoding/csv`.

**Comment by jszwec** [comment]
Im afraid I don't quite understand what kind of disadvantage you see with wrapping these types.

If I understand your proposal correctly and assuming there would be a function/config you would still have to implement an encoding function for each type you need. Even if you go with plain `encoding/csv`.

The custom type + MarshalCSV gives you exactly the same effect and a very similar boilerplate. Perhaps even more readability and reusability.

I would agree with you that it seems unpleasant if we were talking about types like `int`. Because `type Int int` and `int` are not the same thing and you would have to cast it everywhere, while slice and map aliases behave differently. After you defined them you would not even feel they are custom types.

Internally you can keep everything as `[]T` but only your struct should store the right types for the encoding purposes. 

Notice that in the example above that you can pass the custom type `Strings` to `strings.Join` without casting it to `[]string`. The same happens in other direction - you can assign []string to Strings without casting.

**Comment by wavded** [comment]
Thanks for the clarification on casting, I didn't know you could avoid casting slices like that. Learned something today! Seems it would be simplest do that, I'll give it a go and report back if I have any problems.

**Comment by jszwec** [comment]
sounds good, let me know!

**Comment by wavded** [comment]
Working good so far. Appreciate your help @jszwec.

**Comment by jszwec** [comment]
You are welcome. In such case I will close the issue. Feel free to reopen it if anything comes up.
