### ISSUE TITLE
Suggestion for data normalization

### ISSUE THREAD

**Issue by KalleDK** [jszwec/csvutil#12]
Hi

I've done some patching to improve the performance of the data normalization.
It spawned from the fact that I need to unmarshal dates from other formats, and found it strange that when I normalize the field, I have to convert it back to a string, so I added a way to do it directly.

One thing I don't know is, would this mess with your cached part.

When benchmarking with the patch the alloc/op is around 3 times lower after the 100 records mark.

```
BenchmarkUnmarshal/csvutildk.Unmarshal/1_record-8         	  200000	     11239 ns/op	    7902 B/op	      41 allocs/op
BenchmarkUnmarshal/csvutildk.Unmarshal/10_records-8       	   50000	     25840 ns/op	   15054 B/op	      72 allocs/op
BenchmarkUnmarshal/csvutildk.Unmarshal/100_records-8      	   10000	    168801 ns/op	   76848 B/op	     345 allocs/op
BenchmarkUnmarshal/csvutildk.Unmarshal/1000_records-8     	    1000	   1628027 ns/op	  637536 B/op	    3048 allocs/op
BenchmarkUnmarshal/csvutildk.Unmarshal/10000_records-8    	      50	  20540432 ns/op	11187253 B/op	   30059 allocs/op
BenchmarkUnmarshal/csvutildk.Unmarshal/100000_records-8   	       5	 207199960 ns/op	113993987 B/op	  300072 allocs/op
BenchmarkUnmarshal/csvutil.Unmarshal/1_record-8           	  100000	     13039 ns/op	    8238 B/op	      53 allocs/op
BenchmarkUnmarshal/csvutil.Unmarshal/10_records-8         	   30000	     40134 ns/op	   17118 B/op	     138 allocs/op
BenchmarkUnmarshal/csvutil.Unmarshal/100_records-8        	    5000	    315599 ns/op	   96193 B/op	     951 allocs/op
BenchmarkUnmarshal/csvutil.Unmarshal/1000_records-8       	     500	   3046062 ns/op	  829794 B/op	    9054 allocs/op
BenchmarkUnmarshal/csvutil.Unmarshal/10000_records-8      	      50	  33160620 ns/op	13107352 B/op	   90065 allocs/op
BenchmarkUnmarshal/csvutil.Unmarshal/100000_records-8     	       3	 352344833 ns/op	135428960 B/op	  900080 allocs/op
```

Diff: https://github.com/KalleDK/csvutil/commit/787aaf6cc96fb03839d704366d25d528ebfc6cf6
Test: https://gist.github.com/KalleDK/6616d6634a787fa31cfff02c47110f2c

**Comment by KalleDK** [comment]
One thing I'm looking into, is for the method to be a pointer to the correct type instead of an interface{}.

**Comment by KalleDK** [comment]
Also this could "easily" be expanded into the encoder, and thereby allow to encode to custom format.

**Comment by jszwec** [comment]
Hello, thank you for your contribution.

It looks like your proposal is more an addition than optimization. Map function was never meant to parse data to a concrete type, but only to normalize it. That's why it returns a string. It is by design to keep the decoding part in one place and have only one way to do so.

ConvertData function in your benchmark could be much faster than it is. You don't need to time.Parse only to Format it back again, it is very expensive. You could just do some simple format recognition and simply add T00:00:00Z to the end of it. That could give you a boost.

The most performant solution is to create your own [Unmarshaler](https://github.com/jszwec/csvutil#examples_time_format). There will be barely any difference in speed between it and your proposal. Unmarshaler will be a tiny bit slower due to additional reflection checks and a string copy.

I don't think allowing to specify custom decoding functions per decoder is the right way to go. In the long run it would make your code harder to test and maintain. I believe that only types should be responsible for the way they are being encoded or decoded. Std packages likes json have taken the same approach.

**Comment by KalleDK** [comment]
Yeah, I can see it as an addition, I do understand that the ConvertData could be faster, but this was just a simple example. 

The reason for this springs from a problem I keep stumbling into. Right now I'm creating a lib to work with my banks, as in customer not hired, transaction records. I would love for the user to use a type like

```
type Record struct {
   Date *time.Time
   Amount int64
   // Many more fields
}
```

But this will never work due to their csv date is in a custom format. Not all the people I talk to always give me the advise to use a custom type
```
type BankDate *time.Time

func (b *BankDate) Unmarsahl .....

type Record struct {
   Date BankData
   Amount int64
   // Many more fields
}
```
But this forces the users to remember to explicit cast the BankData to *time.Time (and realise they actually can do that) if they want to use it with normal dates (like my guess is most people want).

One thing I could do was have both types, and keep the second internally only, and convert to and from the users.. But I feel that would be a lot of copying for no good reason.

I do though respect your choice if you want to keep it as the std packages does (I do miss the feature in their packages too though).

**Comment by jszwec** [comment]
> But this forces the users to remember to explicit cast the BankData to *time.Time (and realise they actually can do that) if they want to use it with normal dates (like my guess is most people want).

That's why it's better in this case to use embedding instead of type aliasing. With embedding your struct would still behave like time.Time and if someone would like to pass it as `time.Time` then they just have to call `myTime.Time`

> One thing I could do was have both types, and keep the second internally only, and convert to and from the users.. But I feel that would be a lot of copying for no good reason.

This is actually a good idea and an approach I would take. I don't know how you want your package too look like but based on what you said so far, I prepared a little example to show that it is actually not that much work: https://play.golang.org/p/Wv6LmZusoiA

Im on the fence with this proposal mainly because with the current approach all these things can be done usually in a reasonable and elegant way.

**Comment by KalleDK** [comment]
I understand that it's a niche thing I want to achive :) I might have some other proposals later, but I'll close this for now
