### ISSUE TITLE
Support TextMarshaler and TextUnmarshaler interfaces

### ISSUE THREAD

**Issue by cbelsole** [jszwec/csvutil#31]
Go types being serialized often implement [TextMarshaler](https://golang.org/pkg/encoding/#TextMarshaler) and [TextUnmarshaler](https://golang.org/pkg/encoding/#TextUnmarshaler). This can be leveraged the same way as Stringer to provide the values needed to generate a CSV without having to register your type or implement MarshalCSV and UnmarshalCSV especially when types come from third party libraries that you cannot change. 

Suggested order: `MarshalCSV() -> MarshalText() -> String()`

[Example](https://github.com/guregu/null/blob/master/float.go#L122)

**Comment by jszwec** [comment]
Hello, This is already supported. In particular `time.Time` uses it by default: https://github.com/jszwec/csvutil#custom-timetime-format-

**Comment by cbelsole** [comment]
Gotcha. I see how this works now. Maybe we can call this out on the readme explicitly under the marshal/unmarshal section.

**Comment by jszwec** [comment]
I am not convinced if README is the good place for it. I would expect people to read the actual documentation which already contains this information and every other detail about how these functions work:

https://pkg.go.dev/github.com/jszwec/csvutil#Encoder.Encode
https://pkg.go.dev/github.com/jszwec/csvutil#Decoder.Decode

Let me think about it.

**Comment by cbelsole** [comment]
IMO for libraries that are not sufficiently complex, the readme is for giving a board overview of the library. Since the library is for encoding/decoding CSVs one would expect that the readme shows off this functionality in board strokes. 

Also, reading through the code a little it does not look like the Stringer interface is used.

**Comment by jszwec** [comment]
I believe the current readme has plenty of examples that show functionality in broad strokes.

`fmt.Stringer` is not supported by design because it is a one way function. Just like `Marshal` is similar to String, there is no equivalent of `Unmarshal`. 

Take `time.Duration` for example - it has String but in order to parse it you need to call `time.ParseDuration` which is not its method. If we decided to support `fmt.Stringer` by default, then I'm sure we would break existing programs, since a lot of builtin types already support it. If it suddenly started using `String` then you would not be able to Unmarshal it back. Instead now it will encode/decode as int64. The same happens in standard `json` and `xml` packages.

If `fmt.Stringer` fits your use case you can Register this interface and then every implementation will call `String()` method.
```go
enc.Register(func(s fmt.Stringer) ([]byte, error) {
	return []byte(s.String()), nil
})
```

[Full Example](https://github.com/jszwec/csvutil/blob/master/example_encoder_test.go#L183)

**Comment by cbelsole** [comment]
That makes sense. Thanks for the thorough explanation.
