### ISSUE TITLE
Encode may not write all records if buffer fills up?

### ISSUE THREAD

**Issue by keep94** [jszwec/csvutil#36]
I was excited to find this library as I had a lot of boilerplate code to convert go structs to []string and back for writing CSV files with the standard encoding/csv package.

I tried creating a csvutil.Encoder and called Encode() with a slice of 181 structs.  Only 142 of the 181 structs were written out. When I looked at the size of the file produced, it was exactly 12288 bytes which is 12 * 1024.  The last line of the CSV file was a partial write as writing stopped in the middle of one field.  As far as I know, Encode() returned nil for error.

I was expecting Encode() to write out the entire slice I gave it rather than quitting when 12288 bytes were written.

If this is working as designed or if you need more information from me please let me know. Thanks.

**Comment by keep94** [comment]
I just realized that I forgot to call Flush() on the underlying csv.Writer, which explains fully the behavior that I saw.  You may want to consider adding an EncodeFully() method to Encoder that writes out everything being encoded by taking care to call flush on the underlying csv.Writer automatically.  That would save the caller from having to do extra work with the Flush() method when all they really want to do is write an entire slice out to a file.  

By the way, good job on this library.

**Comment by jszwec** [comment]
Thank you, it's good to hear that you find it useful.

Auto flush is very tricky. I am hesitant to touch it, and I can explain why. 

Csvutil is based on interfaces, rather than on csv.Writer and csv.Reader directly. The reason for this is: there are some existing forks of the csv pkg, and custom parsers with similar API. The interface by itself doesn't wrap `Flush` method. It is true that it doesn't have to, and the code could check if it does and call it. 

However, due to the fact that csvutil is based on interfaces, it shouldn't be calling Flush for the same reason as `io.Copy` wouldn't call Flush while writing to `bufio.Writer`. Also, Encoder is not replacing cvs.Writer, it uses it. I feel like it's not its responsibility to call Flush.

`csvutil.Marshal` calls Flush, but it's a different use case and it's documented that it uses csv.Writer specifically.
