### ISSUE TITLE
How to decode CSV files with inconsistent column and struct

### ISSUE THREAD

**Issue by lwlee2608** [jszwec/csvutil#37]
I have a csv that look like this
```csv
1,aa,bb,cc
1,aa,bb,cc
2,aa,dd
1,aa,bb,cc
2,aa,dd
```

If first column is 1, it should map to `Atype`
```go
type Atype struct {
	RecordId int
	Afield   string
	Bfield   string
	Cfield   string
}
```
If first column is 2, it should map to `Btype`
```go
type Btype struct {
	RecordId int
	Afield   string
	Dfield   string
}
```
How can I do it?

**Comment by lwlee2608** [comment]
I attempt to add this feature by add a new method `DecodeRecord(record []string, v interface{})`
https://github.com/lwlee2608/csvutil

This allow me to `csvReader.Read()` before calling `dec.Decode()`

```
		fields, err := csvReader.Read()
		if err == io.EOF {
			break
		}

		if fields[0] == "1" {
			record := AType{}
			decoderA.DecodeRecord(fields, &record)
		} else if fields[0] == "2" {
			record := BType{}
			decoderB.DecodeRecord(fields, &record)
		}
```

But it breaks the `decodeArray` and `decodeSlice` because `decodeStruct` no longer return `EOF`
Do you have any suggestion to tackle this problem?

**Comment by jszwec** [comment]
We cannot introduce the method you proposed. Decoder depends on the header that was either provided, or that was read from the first line. It uses it to map columns to structs, and because of this Decoder must receive a consistent input. If columns are suddenly missing, it is not very clear what we should do. We could consider an improvement that if `records` slice is shorter than the header, then we can try to map as much as we can and ignore the rest. However, I would rather avoid this use case if I can.

To answer your question - No, it is currently impossible to use inconsistent input with different types using a single decoder.

> Do you have any suggestion to tackle this problem?

Yes, it is quite simple - fix the input. You can leverage the fact that csvutil is based on interfaces. There are many ways to do it in an efficient way. For example read your data stream and split it between two decoders like this:

https://play.golang.org/p/vPbDY_GrZA4
```go
package main

import (
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"strings"

	"github.com/jszwec/csvutil"
)

type Atype struct {
	RecordId int
	Afield   string
	Bfield   string
	Cfield   string
}

type Btype struct {
	RecordId int
	Afield   string
	Dfield   string
}

var (
	ATypeHeader []string
	BTypeHeader []string
)

func init() {
	ATypeHeader = mustHeader(Atype{})
	BTypeHeader = mustHeader(Btype{})
}

type reader struct{ rec []string }

func (r reader) Read() ([]string, error) {
	return r.rec, nil
}

func main() {
	const input = `1,aa,bb,cc
1,aa,bb,cc
2,aa,dd
1,aa,bb,cc
2,aa,dd`

	values, err := decodeStrangeFile(strings.NewReader(input))
	if err != nil {
		panic(err)
	}

	for _, v := range values {
		fmt.Printf("%[1]T: %[1]v\n", v)
	}
}

func decodeStrangeFile(r io.Reader) (out []interface{}, _ error) {
	type readerDecoder struct {
		*reader
		*csvutil.Decoder
	}
	newReaderDecoder := func(header []string) readerDecoder {
		r := reader{}
		dec, _ := csvutil.NewDecoder(&r, header...) // you can ignore error when header is specifed
		return readerDecoder{&r, dec}
	}

	decoders := map[string]readerDecoder{
		"1": newReaderDecoder(ATypeHeader),
		"2": newReaderDecoder(BTypeHeader),
	}

	csvReader := csv.NewReader(r)
	csvReader.FieldsPerRecord = -1
	csvReader.ReuseRecord = true
	for {
		rec, err := csvReader.Read()
		if errors.Is(err, io.EOF) {
			return out, nil
		}

		if err != nil {
			return nil, err
		}

		var v interface{}
		switch rec[0] {
		case "1":
			v = &Atype{}
		case "2":
			v = &Btype{}
		default:
			continue
		}

		rdec := decoders[rec[0]]
		rdec.rec = rec
		if err := rdec.Decode(v); err != nil {
			return nil, err
		}
		out = append(out, v)
	}
}

func mustHeader(v interface{}) []string {
	h, err := csvutil.Header(v, "")
	if err != nil {
		panic(err)
	}
	return h
}
```

**Comment by lwlee2608** [comment]
Brilliant!

`type reader struct{ rec []string }` is my missing piece. Didn't know you can do that. 

Thanks for the help
