### ISSUE TITLE
Suggestion on how to iterate the decoder

### ISSUE THREAD

**Issue by dinigo** [jszwec/csvutil#50]
That's a code style option. Id' rather have control in the `for` loop rather than rely in underlaying logic when posible.

Do you think it makes sense to switch the loop in the ["example without header"](https://github.com/jszwec/csvutil#but-my-csv-file-has-no-header-) from the readme to:

```go
	var users []User
	var user User  // no need to create one for each execution, less GC work
	var err error
	// init, check, update in the for loop
	for err = nil; err != io.EOF; err = dec.Decode(&gameRecord) {
		if err != nil {
			log.Fatal(err)
		}
		users = append(users, u)
	}
```

Thanks for your work @jszwec !

**Comment by jszwec** [comment]
No, I believe the example is fine.

 > var user User  // no need to create one for each execution, less GC work
1. Yes, there is a need otherwise it's a bug: Consider the following example: https://go.dev/play/p/tS8c4wKngSr
2. There is no GC work, because user variable doesn't escape, so it's on the stack, not heap
 
```go
 // init, check, update in the for loop
	for err = nil; err != io.EOF; err = dec.Decode(&gameRecord) {
		if err != nil {
			log.Fatal(err)
		}
		users = append(users, u)
	}
```
The for loop pattern in the example is a well established pattern that is used in std json pkg: https://pkg.go.dev/encoding/json#example-Decoder. I dont see a reason why it should be different.

>  Id' rather have control in the for loop rather than rely in underlaying logic when posible.

I am not sure I understand. What can't you control in the for loop from the example?

**Comment by jszwec** [comment]
I see, well... your last example:
```go
// main.go

var user User
var users []User
for dec.Next(&user) {
	users = append(users, user)
}
```

Has exactly the same problem that I mentioned in my previous comment, where a user's fields could be wrong (like age from my playground example). Using `Next` the way you want it, doesn't allow you to fix it. Unless you put Next inside the for loop, which would make this function or "syntactic sugar" useless.
