### ISSUE TITLE
Add a shortcut constructor for a decoder header from type

### ISSUE THREAD

**Issue by narqo** [jszwec/csvutil#58]
Since Go 1.18, the code snippet below (taken from the documentation)

```go
userHeader, _ := csvutil.Header(User{}, "csv")

dec, _ := csvutil.NewDecoder(csvReader, userHeader...)
```

could be folded into a generic constructor:

```go
dec, _ := csvutil.NewDecoderFor[User](csvReader)
```

A simple implementation can look like this:

```go
func NewDecoderFor[T any](r Reader) (*Decoder, error) {
    var v T
    header, err := csvutil.Header(v, "csv")
    if err != nil { ··· }

    return csvutil.NewDecoder(csvReader, header...)
}
```

It's trivial to implement this as a custom wrapper in the user code. But I wanted to check if this something, that can be a potential improvement in the package itself.

**Comment by jszwec** [comment]
I am opposed to this idea because header is optional. The proposed function would solve only the use case where csv input doesn't contain a header, which could also be misused by mistake (e.g. used on a csv input with a header)

Other issue that I see is that one day me way want to introduce a `Decoder[T any]` (for more aggressive caching) in which case we would like to have a function `NewDecoder{For,Of}[T any]` free
