### ISSUE TITLE
simple way to test for MissingColumnsError 

### ISSUE THREAD

**Issue by TomasVojacek** [jszwec/csvutil#64]
Is there way to test MissingColumnsError with errors.Is?

**Comment by jszwec** [comment]
MissingColumns does not support equality operator because slices cannot be compared. Just use errors.As

**Comment by TomasVojacek** [comment]
This behavior io.EOF can not be catch with error.As.
Would it be possible that  MissingColumnsError has wrapped inner constant MissingColumnsError that will be able test with error.Is?

**Comment by jszwec** [comment]
@TomasVojacek no... this is not how errors.Is works ... as I said, you can check it with errors.As. MissingColumnError cannot be compared with `Is` or == operator due to having slice in its struct

This is how you can do it:
https://go.dev/play/p/6zQQbc0nQFK

Please refer to https://pkg.go.dev/errors documentation if something is still unclear.

There is no problem on the csvutil side, closing

**Comment by TomasVojacek** [comment]
I was thinking about solution like this:

var MissingColumnsInnerError = fmt.Errorf("csvutil: missing columns")

func (e *MissingColumnsError) Unwrap() error {
	return MissingColumnsInnerError
}

func TestMissingColumnsError(t *testing.T) {
	err := &MissingColumnsError{}
	if !errors.Is(err, MissingColumnsInnerError) {
		t.Fail()
	}
}

**Comment by jszwec** [comment]
I do not see any value in this since the same can be achieved with errors.As
