### ISSUE TITLE
Custom integer and float type coding

### ISSUE THREAD

**Issue by maciej** [jszwec/csvutil#8]
Currently the only solution for changing the custom coding of int and float types in `csvutil` is by writing a _custom format_ Marshaler/Unmarshaler as described [here](https://github.com/maciej/csvutil#custom-timetime-format-).

This approach forces the user to bend the struct to the codec library.

Compare the following:
```go
type Foo struct {
  MyValue int32
}
```

vs
```go
type Bar struct {
  MyValue FormattedInt32
}

type FormattedInt32 struct {
  TheActualValue int32
}

// FormattedInt32 Marshaler/Unmarshaler implementation follows
```

Not only boilerplate code needs to be written, but the struct is modified to fit the `csvutil` codec.

Following the example of [easycsv](https://github.com/yunabe/easycsv#customizing-decoders) I'd propose adding either:
1. a separate tag `format` or `coding` that would specify the format of int / float types.
2. adding a tag option like `omitempty` with the format specifier

I propose using standard [print verbs](https://golang.org/pkg/fmt/#hdr-Printing)

The above example with int formatted in hexadecimal according to approach 1:
```go
type Foo struct {
   MyValue int32 `csv:"my_val" format:"x"`
}
```

approach 2:
```go
type Foo struct {
   MyValue int32 `csv:"my_val,%x"`
}
```

@jszwec what do you think?

**Comment by jszwec** [comment]
I personally think that it is clean to have only one approach to solve custom encodings and decodings problem. In csvutil it works just like in any other encoding/* package in the standard library. I agree that sometimes it seems inconvenient to be forced to introduce your own type especially when it is a builtin type. However, thanks to using these interfaces your type encodings are consistent. 

The exception of this is Decoder.Map; which, can help you normalize the incoming data that doesn't have to be always consistent. I don't know what is your exact use case, is it about encoding or decoding data?

Easycsv takes a very different approach than csvutil. It also doesn't provide an Encoder. That alone makes a very big difference. I wouldn't like to introduce custom tags that could be available in an Encoder, but not in Decoder.

About approach 1:
`MyValue int32 `csv:"my_val" format:"x"`` I don't think this is a good idea - `format` could conflict with any other package that would be using that tag.

About approach 2:
`MyValue int32 `csv:"my_val,%x"`` Introducing custom formatting like that can create a lot of problems, especially with escaping. If I want to use `"` in my format I have to remember to escape it. Then If I want to use `,` in my tag it's another problem... This brings a lot of parsing problems that could turn against us in the future, bringing additional maintenance burden.

About format approach in general:
Im not a fan of specifying custom formats on per field basis. Like I mentioned above, the type encodings should be consistent. Another thing about it is maintenance on the user side. Formats can be written in a wrong way - eg. someone will forget to escape the double quote. In that case mistakes, will be found in runtime. This will force package users to write tests for each struct using these format tags to ensure correctness. If that was a Marshaler/Unmarshaler one test would take care of that.

By the way you don't need a struct for your `FormattedInt32` - you can use type aliasing thanks to which converting that type will be very easy in the later parts of the code.

```go
type Bar struct {
  Int Int32
}

type Int32 int32

func (n Int32) MarshalCSV() ([]byte, error) {
	var buf [64]byte
	return strconv.AppendInt(buf[:0], int64(n), 10), nil
}

func (n *Int32) UnmarshalCSV(data []byte) error {
	v, err := strconv.ParseInt(string(data), 10, 32)
	*n = Int32(v)
	return err
}
```

Please let me know what is your exact use case and if perhaps Decoder.Map would help you out.

**Comment by jszwec** [comment]
I have given more thought to it, and I think I would be willing to add the following tags:
* `binary`
* `octal`
* `hexadecimal`
They would only work with int types. Their behavior would be similar to `string` tag in `encoding/json` pkg. This means that both Encoder and Decoder would work using the provided base.

Example:
```go
type Foo struct {
  A int `csv:",binary"`
  B int `csv:"b,octal"`
}
```

However, I don't see any value in adding any tags for float's fmt, or precision, because most parsers will be able to take in different formats.

Any other custom formats would have to be solved by Marshaler/Unmarshaler.

Does this solve your case?

**Comment by maciej** [comment]
Thank you for the quick and comprehensive response!

The solution you proposed is not a fit for my case.

```go
type Foo struct {
}

**Comment by maciej** [comment]
Thank you for the quick and comprehensive response!

The solution you proposed is not a fit for my case.

What I ended up doing is extending the struct with another field I populate in a `PreSerialize` step (and conversely I read it in `PostDeserialize`)

```go
type Foo struct {
  realValue float64
  ValueForSerialization string
}
```

As mentioned above I'm dissatisfied with the need for custom types for the purpose of CSV coding. I  also do understand your opposition for using the format string in an untyped field tag.

Another approach that comes to mind is to give the user full control over the cases that the Encoder struggles to handle with flexibility and fidelity by falling back to how one would prepare a record for `csv.Writer` and `csv.Reader` with code similar to:

```go
type Foo struct {
   Bar float64 `csv:"-"`
}

// or "PreCSVWrite"
func (f *Foo) PostCSVEncode(record []string) []string {
  return append(record, strconv.FormatFloat64(…))
}

func (f *Foo) PostCSVDecode(record []string, headerLUT map[string]int) {
   strconv.ParseFloat(record[headerLUT["bar"]] …)
}

// the encoded should also receive a capacity hint to avoid resizing the record
```

I've surveyed the coding space and none of the libraries I looked has such functionality. I looked at tinylib/msgp, encoding/json and easycsv. Am I missing something why that's the case?

**Comment by jszwec** [comment]
I believe the reason for that is that the user already has a full control over how something gets serialized/deserialized. The user defines types and structs according to the specified rules. Builtin types are being encoded in a default way (sometimes according to format spec - like json), other types or custom formats need to have their own type with Marshalers to define how should they be serialized. This makes total sense to me for the reasons I said before. It's about how you encode the each value of a type, not a specific value. That's why `encoding.TextMarshaler` exists and some types like `time.Time` support it. Because this is the consistent way of how `time.Time` should encode itself into a string.

If user had to write his own methods like you proposed, then most likely it would make more sense just to encode `[]string` yourself and send it to csv.Writer. Csvutil wouldn't make much sense anymore. Also, you are getting the boilerplate either way due to the fact you have to encode it yourself somewhere.

If your only problem here is the custom type itself, it's not really a big problem, you can kind of avoid it in your main struct by taking the following approach:

```go
type Foo struct {
  A string  `csv:"a"`
  B int     `csv:"b"`
  C float64 `csv:"-"` 
}

type foo struct {
  *Foo
  C myType `csv:"c"`
}

type myType float64

// Marshaler/Unmarshaler implementations

// lets say Encode is the function where you encode your data
func Encode(w io.Writer, fs []Foo) error {
  csvw := csv.NewWriter(w)
  enc := csvutil.NewEncoder(csvw)
  for _, f := range Foo {
     if err := enc.Encode(foo{f, myType(f.C)}); err != nil {
       return err
     }
  }
  csvw.Flush()
  return csvw.Error()
}

// same with decoder - you decode into foo and create Foo out of it by setting the C field
func Decode() error {
 ...
 ...
 var v foo
 err := dec.Decode(&v)
 // error handling ...
 // ...

 // perhaps you could build Foo methods to do these for you.
 f := *v.Foo
 f.C = v.C
}
```

Like I mentioned, you will end up with a boilerplate somewhere. It will be either writing your own type and Marshaler/Unmarshaler, or some other custom formatting function. It's just a nature of this language.
